name: KenyaEMR CI

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:
    types:
      - created

env:
  FORCE_COLOR: true
  env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'yarn'

      - name: Setup Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Build packages
        run: |
          yarn turbo run build \
            --concurrency=10 \
            --cache-dir=".turbo" \
            --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packages/**/dist
            .turbo
          compression-level: 9
          retention-days: 7

  pre_release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Download artifacts and turbo cache
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: .

      - name: Restore Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Version
        run: yarn workspaces foreach --worktree --topological --exclude @kenyaemr/esm-3.x-apps version "$(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.${{ github.run_number }}"

      - name: Build
        run: yarn turbo run build --cache-dir=".turbo" --concurrency=5 --no-daemon
        env:
          TURBO_CACHE_KEY: ${{ github.sha }}

      - name: Configure Git
        run: |
          git config user.email "info@thepalladiumgroup.com"
          git config user.name "KenyaEMR CI"

      - name: Publish pre-release
        run: |
          yarn config set npmAuthToken "${NODE_AUTH_TOKEN}"
          yarn run ci:prepublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

  # dev server build dispatch
  Trigger_server_build:
      runs-on: ubuntu-latest
      needs: pre_release
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Invoke workflow without inputs. Don't wait for result
          uses: aurelien-baudet/workflow-dispatch@v2
          with:
            workflow: KenyaEMR CI
            repo: palladiumkenya/openmrs-config-kenyaemr
            token: ${{ secrets.PERSONAL_TOKENS }}
            wait-for-completion: false 

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Download build artifacts and turbo cache
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: .

      - name: Restore Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      
      - name: Build
        run: yarn turbo run build --cache-dir=".turbo" --concurrency=5 --no-daemon

      - name: Publish release
        run: |
          yarn config set npmAuthToken "${NODE_AUTH_TOKEN}"
          yarn run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}